### ISSUE TITLE
Build error meta-toolchain with rust

### ISSUE THREAD

**Issue by ReadyMark** [meta-rust/meta-rust#403]
## Version(s) of meta-rust
53bfa324891966a2daf5d36dc13d4a43725aebed
## Version(s) of poky and/or oe-core
d88d62c20d7d8da85f02edb170dae0280624ad7e
## Expected result
would build successfully. 
## Actual result
Log data follows:
| DEBUG: Executing shell function do_compile
| COMPILE rust build
| running: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rust-snapshot/bin/cargo build --manifest-path /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rustc-1.46.0-src/src/bootstrap/Cargo.toml --frozen
|     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
| running: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rustc-1.46.0-src/build/bootstrap/debug/bootstrap -j 32 build --verbose
|
|
| failed to execute command: "/home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/recipe-sysroot/usr/lib/llvm-rust/bin/llvm-config" "--bindir"
| error: No such file or directory (os error 2)
|
|
| Traceback (most recent call last):
|   File "src/bootstrap/bootstrap.py", line 998, in <module>
|     main()
|   File "src/bootstrap/bootstrap.py", line 981, in main
|     bootstrap(help_triggered)
|   File "src/bootstrap/bootstrap.py", line 967, in bootstrap
|     run(args, env=env, verbose=build.verbose)
|   File "src/bootstrap/bootstrap.py", line 143, in run
|     raise RuntimeError(err)
| RuntimeError: failed to run: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rustc-1.46.0-src/build/bootstrap/debug/bootstrap -j 32 build --verbose
| WARNING: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/temp/run.do_compile.679:1 exit 1 from 'python3 src/bootstrap/bootstrap.py -j 32 "$@" --verbose'
| ERROR: Execution of '/home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/temp/run.do_compile.679' failed with exit code 1:
| COMPILE rust build
| running: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rust-snapshot/bin/cargo build --manifest-path /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rustc-1.46.0-src/src/bootstrap/Cargo.toml --frozen
|     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
| running: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rustc-1.46.0-src/build/bootstrap/debug/bootstrap -j 32 build --verbose
|
|
| failed to execute command: "/home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/recipe-sysroot/usr/lib/llvm-rust/bin/llvm-config" "--bindir"
| error: No such file or directory (os error 2)
|
|
| Traceback (most recent call last):
|   File "src/bootstrap/bootstrap.py", line 998, in <module>
|     main()
|   File "src/bootstrap/bootstrap.py", line 981, in main
|     bootstrap(help_triggered)
|   File "src/bootstrap/bootstrap.py", line 967, in bootstrap
|     run(args, env=env, verbose=build.verbose)
|   File "src/bootstrap/bootstrap.py", line 143, in run
|     raise RuntimeError(err)
| RuntimeError: failed to run: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/rustc-1.46.0-src/build/bootstrap/debug/bootstrap -j 32 build --verbose
| WARNING: /home/rootech/imx-yocto-bsp/A7300/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/rust/1.46.0-r0/temp/run.do_compile.679:1 exit 1 from 'python3 src/bootstrap/bootstrap.py -j 32 "$@" --verbose'
|
ERROR: Task (/home/rootech/imx-yocto-bsp/sources/meta-rust/recipes-devtools/rust/rust_1.46.0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3365 tasks of which 3359 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/rootech/imx-yocto-bsp/sources/meta-rust/recipes-devtools/rust/rust_1.46.0.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

## Steps to reproduce
1. add to conf/local.conf
 TOOLCHAIN_TARGET_TASK_append = " rust clang"

2. build
bitbake meta-toolchain

**Comment by ReadyMark** [comment]
I am sorry this issue would be same as listed in TODO. so, I close it Thanks.
